### ISSUE TITLE
Upgrade Highcharts library

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-sencha#88]
Ideally we'd take 6.2.0, however this change is motivated by the need for the tooltip config 'outside', which is included as of 6.1.1. 

In a Sencha based client app, we now have a set of narrow charts in which our tooltip can render covered up on either side (worse and worse as your browser gets narrower). The 'outside' config will allow the tooltips to break out of the associated chart like a popover.

I attempted to do this upgrade (to both versions mentioned above). In both cases, Highcharts is throwing errors:

highstock.src.js?compile=false:2109 Error: <rect> attribute y: Expected length, "NaN".
_defaultSetter @ highstock.src.js?compile=false:2109
highstock.src.js?compile=false:2109 Error: <rect> attribute height: Expected length, "NaN".
_defaultSetter @ highstock.src.js?compile=false:2109
highstock.src.js?compile=false:2109 Error: <rect> attribute y: Expected length, "NaN".
_defaultSetter @ highstock.src.js?compile=false:2109
highstock.src.js?compile=false:2109 Error: <rect> attribute height: Expected length, "NaN".
_defaultSetter @ highstock.src.js?compile=false:2109

I looked into this quite a bit and some with Colin before Lee thought it might be better to file this and take care of more pressing matters for the moment. Stepping through the Highcharts code it appears it could have something to do with the way we set extremes. Colin also theorizes that some regex could be getting garbled by the asset pipeline but we couldn't pin it down in either case.

**Comment by febbraiod** [comment]
Should look to upgrade to the latest if possible (7)

**Comment by febbraiod** [comment]
At first blush HS 7.0.2 seems to have cleared up the problem described above, and I have confirmed that the outside tooltip property is working in PIQ.

**Comment by febbraiod** [comment]
Upgrade looks good. No visible problems in PIQ caused by the upgrade. I also went through the release notes from Highcharts/HighStock (going back to our current version) and didn't seeing anything that caused me any alarm. Will open a PR shortly.

A couple of notes that I thought had an outside chance of effecting client apps are:

*If the chart.height setting is higher than the CSS height of the container, the chart will now be clipped. This is a consequence of adapting the chart to table cells and flex layouts.

*Highcharts now makes room for the legend in the layout if it has verticalAlign: 'top' with a horizontal legend. In existing charts using this layout, the layout of the legend and the plot area may be affected.

**Comment by lbwexler** [comment]
NPTF
