### ISSUE TITLE
Exiting impersonation in mobile throws

### ISSUE THREAD

**Issue by febbraiod** [xh/hoist-sencha#97]
On XH.getViewport.mask(). 

Observed many times in flagship client app. More details coming soon.

**Comment by febbraiod** [comment]
In identityService Our code calls:  
return XH.requestAsync({url:"/hoistImpl/endImpersonate"}).then(function() {
    **XH.getViewport().mask();**
    window.location = "/";

Which causes this to throw in Ext:
render:function(container, insertBeforeElement) {
  if (container && container.isWidget) {
    container = container.el;
  }
  **var dom = this.renderElement.dom**, containerDom = Ext.getDom(container), insertBeforeChildDom;
...

**Comment by febbraiod** [comment]
In order to trigger, one must impersonate the **navigate to a module** then exit impersonation.

The nav part makes me suspect the carousel/routing/viewport code. The odd part is if you navigate from the base route to the dashboard and then exit we don't have this problem, you have to go to a module specifically.

**Comment by lbwexler** [comment]
NPTF
